// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8lNDkxjlkZ_ByAaMN4Ycq2g7whkQ81k',
    appId: '1:1079075436971:web:d6c7649ab0d1f4c77abaee',
    messagingSenderId: '1079075436971',
    projectId: 'flutter-test-3c6c5',
    authDomain: 'flutter-test-3c6c5.firebaseapp.com',
    storageBucket: 'flutter-test-3c6c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1vr7YUkfxhFWgueYoTqMpuahrBdhCa4I',
    appId: '1:1079075436971:android:aaf9b90f867f0a997abaee',
    messagingSenderId: '1079075436971',
    projectId: 'flutter-test-3c6c5',
    storageBucket: 'flutter-test-3c6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD5ojbAdqfhQylbJ4yeJIlh2U-VDw7WQI',
    appId: '1:1079075436971:ios:a83e4a8073ff876a7abaee',
    messagingSenderId: '1079075436971',
    projectId: 'flutter-test-3c6c5',
    storageBucket: 'flutter-test-3c6c5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD5ojbAdqfhQylbJ4yeJIlh2U-VDw7WQI',
    appId: '1:1079075436971:ios:a83e4a8073ff876a7abaee',
    messagingSenderId: '1079075436971',
    projectId: 'flutter-test-3c6c5',
    storageBucket: 'flutter-test-3c6c5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
